apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.namespaces.backend | quote }}
data:
  REDIS_HOST: {{ include "devops-app.redisDns" . | quote }}
  REDIS_PORT: {{ .Values.backend.config.redisPort | quote }}
  POSTGRES_HOST: {{ include "devops-app.postgresDns" . | quote }}
  POSTGRES_PORT: {{ .Values.backend.config.postgresPort | quote }}
  POSTGRES_DB: {{ .Values.backend.config.postgresDb | quote }}
